export const token = {
VIDEO_API_ACCESS_TOKEN : "MjIwNTcwXzE3NTE3ODUyNzBfNTBlNGZjZmIxYzM0OGU5MDUwNGY2YjhjOGY4MjUyZjNmOWZhMGY0OA==",
EMDED_TOKEN : "MjIwNTcwXzE3NTE3ODUyNzBfOTEyZjk4OGZjNDE2NzI4MjY3MTU1NTUxZjczYTM4M2Y1YWYwZWM5ZQ=="
}